/*******************************************************************************
 * Copyright (c) 2023 Vector Informatik GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Vector Informatik GmbH - initial API and implementation
 *******************************************************************************/
package org.eclipse.ui.internal.findandreplace;

/**
 * Avoid using this class. It is used as a glue to correctly map to the
 * error-messages generated by RegEx-Errors which are directly displayed in
 * plain text.
 *
 * Prefer using and extending {@link FindReplaceLogicStatus}
 */
public class FindReplaceLogicMessage implements IFindReplaceLogicStatus {

	private String message;

	public FindReplaceLogicMessage(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	@Override
	public <T> T visit(IFindReplaceLogicStatusVisitor<T> visitor) {
		return visitor.visit(this);
	}

}
